import { _electron as electron } from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { resolveBinary } from '../src/main/engine/binaryManager.js';
import { rankCandidates } from '../src/main/engine/matching.js';

const root = await fs.mkdtemp(path.join(os.tmpdir(), 'deckprep-e2e-'));
const source = path.join(root, 'עומר - Test song.wav');
const destination = path.join(root, 'crate');
await fs.mkdir(destination);
const ffmpeg = await resolveBinary('ffmpeg');
await promisify(execFile)(ffmpeg, ['-y', '-f', 'lavfi', '-i', 'sine=frequency=440:duration=3', '-af', 'apad=pad_dur=15', source]);
const original = await fs.readFile(source);
let application;
try {
  const executable = process.env.DECKPREP_TEST_EXE;
  application = await electron.launch({...(executable ? {executablePath: executable} : {}), args: [...(executable ? [] : ['.']), '--test-user-data=' + path.join(root, 'state')], timeout: 30000});
  await application.evaluate(({dialog}, data) => {
    dialog.showOpenDialog = async (...args) => {
      const options = args.at(-1);
      return {canceled: false, filePaths: options.title?.includes('destination') ? [data.destination] : [data.source]};
    };
  }, {source, destination});
  let page = await application.firstWindow();
  let maximized = false;
  for (let attempt = 0; attempt < 40; attempt++) {
    maximized = await application.evaluate(({BrowserWindow}) => BrowserWindow.getAllWindows()[0].isMaximized());
    if (maximized) break;
    await new Promise(resolve => setTimeout(resolve, 100));
  }
  assert.equal(maximized, true, 'the main window should open maximized');
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.locator('#localFilesBtn').click();
  await page.waitForFunction(() => document.querySelectorAll('tr[data-index]').length === 1);
  await page.locator('#browseBtn').click();
  assert.match(await page.locator('#startBtn').innerText(), /Prepare selected/);
  assert.equal(await page.locator('.support-menu').evaluate(element => element.open), false);
  await page.locator('#startBtn').click();
  await page.waitForFunction(() => document.querySelector('.status-chip')?.textContent === 'Review ending');
  await page.waitForFunction(() => document.querySelector('#cancelBtn').disabled);
  await page.locator('tr[data-index]').click();
  await page.waitForFunction(() => document.querySelector('audio')?.duration > 17);
  await fs.mkdir('dist', {recursive: true});
  await page.screenshot({path: 'dist/qa-audio-review-beta10.png'});
  await application.close();
  application = await electron.launch({...(executable ? {executablePath: executable} : {}), args: [...(executable ? [] : ['.']), '--test-user-data=' + path.join(root, 'state')], timeout: 30000});
  page = await application.firstWindow();
  page.on('pageerror', error => errors.push(error.message));
  await page.locator('#resumeSessionBtn').click();
  await page.waitForFunction(() => document.querySelector('.status-chip')?.textContent === 'Review ending');
  await page.locator('tr[data-index]').click();
  await page.waitForFunction(() => document.querySelector('audio')?.duration > 17);
  await page.locator('#audioReview input').fill('5');
  await page.getByRole('button', {name: 'Approve trimmed export'}).click();
  await page.locator('#startBtn').click();
  await page.waitForFunction(() => document.querySelector('.status-chip')?.textContent === 'Verified');
  assert.match(await page.locator('#exportCrateBtn').innerText(), /Create playlist file/);
  await page.waitForFunction(() => document.querySelector('#cancelBtn').disabled);
  await page.locator('#exportCrateBtn').click();
  await page.waitForFunction(() => document.querySelector('#summaryBanner').textContent.includes('verified tracks exported'));
  const files = await fs.readdir(destination);
  assert.ok(files.some(file => file.endsWith('.m3u8')));
  const manifest = JSON.parse(await fs.readFile(path.join(destination, files.find(file => file.endsWith('.mp3.deckprep.json'))), 'utf8'));
  assert.ok(Math.abs(manifest.verification.durationSec - 5) < 0.1);
  assert.equal(manifest.trimDecision.action, 'trim');
  assert.deepEqual(await fs.readFile(source), original);
  await page.screenshot({path: 'dist/qa-crate-export-beta10.png'});
  assert.deepEqual(errors, []);
  const security = await application.evaluate(({BrowserWindow}) => BrowserWindow.getAllWindows()[0].webContents.getLastWebPreferences());
  assert.equal(security.sandbox, true); assert.equal(security.contextIsolation, true); assert.equal(security.nodeIntegration, false);
  await page.locator('#closeDetailBtn').click();
  const scale = [];
  for (const count of [100, 500, 1000]) {
    await page.locator('#inputSource').fill(Array.from({length: count}, (_, i) => `Artist ${i} - Track ${i}`).join('\n'));
    const start = Date.now(); await page.locator('#analyzeBtn').click();
    await page.waitForFunction(expected => document.querySelectorAll('tr[data-index]').length === expected, count);
    const renderMs = Date.now() - start;
    const searchStart = Date.now(); await page.locator('#queueSearch').fill('Track 19');
    await page.waitForFunction(() => document.querySelector('#visibleCount').textContent.includes('shown'));
    scale.push({count, loadAndRenderMs: renderMs, searchMs: Date.now() - searchStart});
    await page.locator('#queueSearch').fill('');
  }
  await application.close();
  application = null;
  const wrongUrl = 'https://www.youtube.com/watch?v=wrong-version';
  const requested = {id: 'test-version-conflict', artist: 'Kerri Chandler, Troy Denari', title: 'The Way It Goes', mix: 'Chris Stassy Remix', durationSec: 488, source: 'spotify', selected: true, status: 'pending'};
  const wrong = {url: wrongUrl, title: 'Kerri Chandler feat. Troy Denari - The Way It Goes (Original Mix, Long Club Version)', artist: 'Kerri Chandler', durationSec: 488, provider: 'YouTube'};
  const candidates = rankCandidates(requested, [wrong]).candidates;
  assert.equal(candidates[0].evidence.versionCompatible, false);
  const exportedAudio = path.join(destination, files.find(file => file.endsWith('.mp3')));
  const completed = Array.from({length: 30}, (_, index) => ({id: `verified-${index}`, artist: 'Generated', title: `Verified ${index}`, selected: false, status: 'done', outputPath: exportedAudio}));
  await fs.writeFile(path.join(root, 'state', 'session.json'), JSON.stringify({version: 2, source: 'spotify', collection: {title: 'Version review'}, tracks: [{...requested, candidates, matchUrl: wrongUrl, matchState: 'chosen'}, ...completed]}));
  application = await electron.launch({...(executable ? {executablePath: executable} : {}), args: [...(executable ? [] : ['.']), '--test-user-data=' + path.join(root, 'state')], timeout: 30000});
  page = await application.firstWindow();
  page.on('pageerror', error => errors.push(error.message));
  await page.locator('#resumeSessionBtn').click();
  const competingImport = await page.evaluate(() => window.djAPI.parseInput('Artist - Competing track'));
  assert.equal(competingImport.success, false, 'import should wait for restore validation');
  const competingLocal = await page.evaluate(() => window.djAPI.importLocal(false));
  assert.equal(competingLocal.success, false, 'local import should wait for restore validation');
  const competingExport = await page.evaluate(() => window.djAPI.exportCrate([1]));
  assert.equal(competingExport.success, false, 'crate export should wait for restore validation');
  await page.locator('#cancelRestoreBtn').click();
  await page.waitForFunction(() => !document.getElementById('resumeSessionBtn').disabled);
  assert.equal(await page.locator('#restoreDialog').isVisible(), true, 'cancelled restore keeps the saved queue available');
  await page.locator('#resumeSessionBtn').click();
  await page.locator('tr[data-index]').first().click();
  const conflictingChoice = page.locator('.candidate').first();
  assert.match(await conflictingChoice.innerText(), /Original Mix, Long Club Version/);
  assert.equal(await conflictingChoice.isDisabled(), true);
  assert.match(await conflictingChoice.innerText(), /Wrong version/);
  assert.match(await conflictingChoice.innerText(), /conflicts with the requested Chris Stassy Remix/);
  assert.equal(await conflictingChoice.evaluate(element => getComputedStyle(element).opacity), '1');
  assert.equal(await conflictingChoice.locator('strong').evaluate(element => getComputedStyle(element).whiteSpace), 'normal');
  assert.match(await page.locator('#detailHelp').innerText(), /conflicts with the requested version/);
  const manualChoice = await page.evaluate(url => window.djAPI.chooseMatch(1, url), wrongUrl);
  assert.equal(manualChoice.success, false);
  assert.match(manualChoice.error, /conflicts with the requested version/);
  await page.screenshot({path: 'dist/qa-match-review-beta10.png'});
  assert.deepEqual(errors, []);
  console.log('Synthetic desktop queue timings:', JSON.stringify(scale));
  console.log('PASS Electron: local import -> inspection -> preview -> restore -> approved trim -> verified M3U8, originals preserved; restore cancellation/operation exclusion and incompatible match rejection verified in real IPC; sandbox enabled, no renderer errors');
} finally {
  await application?.close();
  await fs.rm(root, {recursive: true, force: true});
}
